# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose and provides development-specific settings

services:
  app:
    # Mount source code for development
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    # Override environment for development
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - REDIS_URL=redis://redis:6379/0
    # Enable auto-reload for development
    command: ["python", "app/main.py"]
    depends_on:
      - redis



  # Development Redis with persistent data
  redis:
    volumes:
      - redis_data:/data

# Development-specific volumes
volumes:
  redis_data:
    driver: local