"""
Utility functions for Flask TTS API
"""

from .audio_processor import AudioProcessor
from .security import SecurityUtils
from .tenant_manager import TenantManager, tenant_manager, TenantContext, require_tenant_context, tenant_aware, with_organization_context
from .websocket_manager import WebSocketManager, get_websocket_manager
from .progress_streamer import (
    ProgressStreamingService,
    ProgressTracker,
    ProgressStatus,
    get_progress_streamer,
    create_progress_tracker,
    update_progress,
    subscribe_to_request,
    unsubscribe_from_request,
    mark_request_completed,
    mark_request_failed,
    cancel_request
)
from .websocket_auth import WebSocketAuthMiddleware, get_websocket_auth
from .websocket_health import (
    WebSocketHealthMonitor,
    HealthStatus,
    get_websocket_health_monitor,
    register_connection_health,
    unregister_connection_health,
    record_ping_health,
    record_pong_health,
    record_message_health,
    record_error_health,
    get_connection_health_info,
    get_health_summary,
    get_unhealthy_connections
)
from .analytics_service import AnalyticsService, analytics_service
from .metrics_collector import MetricsCollector, metrics_collector
from .plugin_interface import (
    PluginBase,
    TTSPlugin,
    AudioEnhancementPlugin,
    WebhookPlugin,
    PluginRegistry,
    PluginFactory,
    plugin_registry,
    HookType,
    EventType,
    HookContext,
    EventContext,
    initialize_plugin,
    cleanup_plugin,
    get_plugin_by_name,
    get_all_plugins,
    register_plugin_hook,
    register_plugin_event_handler
)
from .plugin_security import (
    PluginSecurityManager,
    SecurityValidator,
    PluginSandbox,
    CodeAnalyzer,
    PermissionManager,
    ResourceMonitor,
    security_manager,
    SecurityLevel,
    SecurityThreat,
    SecurityViolation,
    SandboxConfig
)
from .plugin_manager import (
    PluginManager,
    PluginLoader,
    PluginLifecycleManager,
    DependencyResolver,
    plugin_manager,
    PluginLoadResult,
    PluginDependencyInfo
)

__all__ = [
    'AudioProcessor',
    'SecurityUtils',
    'WebSocketManager',
    'get_websocket_manager',
    'ProgressStreamingService',
    'ProgressTracker',
    'ProgressStatus',
    'get_progress_streamer',
    'create_progress_tracker',
    'update_progress',
    'subscribe_to_request',
    'unsubscribe_from_request',
    'mark_request_completed',
    'mark_request_failed',
    'cancel_request',
    'WebSocketAuthMiddleware',
    'get_websocket_auth',
    'WebSocketHealthMonitor',
    'HealthStatus',
    'get_websocket_health_monitor',
    'register_connection_health',
    'unregister_connection_health',
    'record_ping_health',
    'record_pong_health',
    'record_message_health',
    'record_error_health',
    'get_connection_health_info',
    'get_health_summary',
    'get_unhealthy_connections',
    'TenantManager',
    'tenant_manager',
    'TenantContext',
    'require_tenant_context',
    'tenant_aware',
    'with_organization_context',
    'AnalyticsService',
    'analytics_service',
    'MetricsCollector',
    'metrics_collector',
    'PluginBase',
    'TTSPlugin',
    'AudioEnhancementPlugin',
    'WebhookPlugin',
    'PluginRegistry',
    'PluginFactory',
    'plugin_registry',
    'HookType',
    'EventType',
    'HookContext',
    'EventContext',
    'initialize_plugin',
    'cleanup_plugin',
    'get_plugin_by_name',
    'get_all_plugins',
    'register_plugin_hook',
    'register_plugin_event_handler',
    'PluginSecurityManager',
    'SecurityValidator',
    'PluginSandbox',
    'CodeAnalyzer',
    'PermissionManager',
    'ResourceMonitor',
    'security_manager',
    'SecurityLevel',
    'SecurityThreat',
    'SecurityViolation',
    'SandboxConfig',
    'PluginManager',
    'PluginLoader',
    'PluginLifecycleManager',
    'DependencyResolver',
    'plugin_manager',
    'PluginLoadResult',
    'PluginDependencyInfo'
]